  
version: "3.5"
services:
  postgres:
    image: postgres:9.5
    container_name: covid_tracking_postgres
    image: postgis/postgis
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    networks:
      - postgres
    volumes:
      - ./postgres_data:/data/postgres

volumes:
  postgres_data:

networks:
  postgres:
    driver: bridge